'use client';
import { useEffect,useMemo,useRef,useState } from 'react';
import type { PointerEvent as ReactPointerEvent } from 'react';
import { angleAt,parseDimension,pointFromLengthAngle,polygonArea,polygonPerimeter,resizeOrthogonalWall,resizeWallKeepingAdjacent } from '../../lib/geometry';
import { dragWallFromStart } from '../../lib/geometry/wall-drag';
import { calculateEstimate } from '../../lib/estimate';
import { CeilingProject,createProjectId,loadProjects,upsertProject } from '../../lib/project';
import './planner.css';import './planner-next.css';

type Point={x:number;y:number};type ElementType='spot'|'chandelier'|'lightLine'|'cornice';type Item={id:number;type:ElementType;x:number;y:number;x2?:number;y2?:number};type History={points:Point[];items:Item[]};type Variant={id:string;name:string;points:Point[];items:Item[]};
const W=900,H=620,initial:Point[]=[{x:120,y:100},{x:780,y:100},{x:780,y:520},{x:120,y:520}];
const labels:Record<ElementType,string>={spot:'Точечный светильник',chandelier:'Люстра',lightLine:'Световая линия',cornice:'Карниз'},prices:Record<ElementType,number>={spot:700,chandelier:1200,lightLine:950,cornice:650},units:Record<ElementType,string>={spot:'шт.',chandelier:'шт.',lightLine:'м.п.',cornice:'м.п.'};
const cloneP=(p:Point[])=>p.map(x=>({...x})),cloneI=(v:Item[])=>v.map(x=>({...x})),snap=(v:number,s:number)=>Math.round(v/s)*s,dist=(a:Point,b:Point)=>Math.hypot(b.x-a.x,b.y-a.y),toMm=(p:Point[])=>p.map(x=>({x:x.x*10,y:x.y*10})),fromMm=(p:Point[])=>p.map(x=>({x:x.x/10,y:x.y/10})),toMmItem=(x:Item)=>({...x,x:x.x*10,y:x.y*10,x2:x.x2===undefined?undefined:x.x2*10,y2:x.y2===undefined?undefined:x.y2*10}),fromMmItem=(x:Item)=>({...x,x:x.x/10,y:x.y/10,x2:x.x2===undefined?undefined:x.x2/10,y2:x.y2===undefined?undefined:x.y2/10});
const pricesConfig={canvasPricePerM2:900,profilePricePerM:350,insertPricePerM:120,fastenerPricePerM:45,spotlightPrice:700,chandelierPrice:1200,lightLinePricePerM:950,cornicePricePerM:650,wastePercent:7,laborPricePerM2:500};

export default function PlannerWorkspace(){
 const [projects,setProjects]=useState<CeilingProject[]>([]),[projectId,setProjectId]=useState(''),[projectName,setProjectName]=useState('Новая комната');
 const [points,setPoints]=useState(initial),[items,setItems]=useState<Item[]>([]),[variants,setVariants]=useState<Variant[]>([{id:'standard',name:'Стандарт',points:cloneP(initial),items:[]}]),[activeVariant,setActiveVariant]=useState('standard');
 const [tool,setTool]=useState<'select'|'draw'|'diagonal'|ElementType>('select'),[orthogonal,setOrthogonal]=useState(true),[grid,setGrid]=useState(50),[zoom,setZoom]=useState(1);
 const [selectedPoint,setSelectedPoint]=useState<number|null>(null),[selectedWall,setSelectedWall]=useState<number|null>(null),[selectedItem,setSelectedItem]=useState<number|null>(null),[selectedDiagonal,setSelectedDiagonal]=useState(1);
 const [showAngles,setShowAngles]=useState(true),[showSideLengths,setShowSideLengths]=useState(true),[showDiagonals,setShowDiagonals]=useState(true),[history,setHistory]=useState<History[]>([]),[future,setFuture]=useState<History[]>([]),[ready,setReady]=useState(false),[status,setStatus]=useState('');
 const [drawing,setDrawing]=useState<Point[]>([]),[drawCursor,setDrawCursor]=useState<Point|null>(null),[sideLength,setSideLength]=useState(''),[sideAngle,setSideAngle]=useState('0'),[drawLengthInput,setDrawLengthInput]=useState(''),[drawAngleInput,setDrawAngleInput]=useState('');
 const svgRef=useRef<SVGSVGElement|null>(null);
 const wallDragRef=useRef<{index:number;startPointer:Point;startPoints:Point[]}|null>(null);
 const area=useMemo(()=>polygonArea(points)/10000,[points]),perimeter=useMemo(()=>polygonPerimeter(points)/100,[points]);
 const estimate=useMemo(()=>calculateEstimate(toMm(points),items.map(x=>({...toMmItem(x),price:prices[x.type]})),pricesConfig),[points,items]);
 const pos=(e:ReactPointerEvent<SVGElement>|PointerEvent):Point=>{const svg=svgRef.current,r=svg?.getBoundingClientRect();if(!r)return{x:0,y:0};return{x:Math.max(0,Math.min(W,((e.clientX-r.left)/r.width)*W/zoom)),y:Math.max(0,Math.min(H,((e.clientY-r.top)/r.height)*H/zoom))};};
 const snapshot=():History=>({points:cloneP(points),items:cloneI(items)});const commit=(p:Point[],i=items)=>{setHistory(h=>[...h.slice(-49),snapshot()]);setFuture([]);setPoints(p);setItems(i);};
 const undo=()=>{const s=history.at(-1);if(!s)return;setFuture(f=>[...f.slice(-49),snapshot()]);setHistory(h=>h.slice(0,-1));setPoints(s.points);setItems(s.items)};const redo=()=>{const s=future.at(-1);if(!s)return;setHistory(h=>[...h.slice(-49),snapshot()]);setFuture(f=>f.slice(0,-1));setPoints(s.points);setItems(s.items)};
 function currentProject():CeilingProject{const vs=variants.map(v=>v.id===activeVariant?{...v,points:cloneP(points),items:cloneI(items)}:{...v,points:cloneP(v.points),items:cloneI(v.items)});return{id:projectId||createProjectId(),name:projectName.trim()||'Без названия',updatedAt:new Date().toISOString(),points:toMm(points),elements:items.map(x=>({...toMmItem(x),price:prices[x.type]})),prices:pricesConfig,client:{name:'',phone:'',address:''},notes:'',orthogonalMode:orthogonal,variants:vs.map(v=>({id:v.id,name:v.name,price:v.id===activeVariant?estimate.totalSell:0,points:toMm(v.points),elements:v.items.map(x=>({...toMmItem(x),price:prices[x.type]}))})),activeVariantId:activeVariant};}
 function save(message='Сохранено'){const p=currentProject(),next=upsertProject(p,loadProjects());setProjects(next);setProjectId(p.id);setStatus(message)}
 function openProject(p:CeilingProject){const raw=p.variants?.length?p.variants:[{id:'standard',name:'Стандарт',points:p.points,elements:p.elements}];const vs=raw.map(v=>({id:v.id,name:v.name,points:fromMm(v.points??p.points),items:(v.elements??p.elements).map(fromMmItem)}));const a=vs.find(v=>v.id===p.activeVariantId)??vs[0];setProjectId(p.id);setProjectName(p.name);setVariants(vs);setActiveVariant(a.id);setPoints(cloneP(a.points));setItems(cloneI(a.items));setOrthogonal(p.orthogonalMode??true);setHistory([]);setFuture([]);setDrawing([]);setDrawCursor(null);setStatus('Проект открыт')}
 useEffect(()=>{const p=loadProjects();setProjects(p);if(p[0])openProject(p[0]);setReady(true)},[]);useEffect(()=>{if(!ready||!projectId)return;const t=window.setTimeout(()=>save('Автосохранено'),900);return()=>window.clearTimeout(t)},[ready,projectId,projectName,points,items,variants,activeVariant,orthogonal]);
 function drawingPoint(raw:Point){const step=grid/10;let q={x:snap(raw.x,step),y:snap(raw.y,step)};if(orthogonal&&drawing.length){const last=drawing[drawing.length-1];const dx=q.x-last.x,dy=q.y-last.y;q=Math.abs(dx)>=Math.abs(dy)?{x:q.x,y:last.y}:{x:last.x,y:q.y};}return q}
 function constrainedDrawPoint(){if(!drawing.length||!drawCursor)return null;const start=drawing[drawing.length-1],length=parseDimension(drawLengthInput),angle=Number(drawAngleInput.replace(',','.'));if(length&&Number.isFinite(angle)){const p=pointFromLengthAngle({x:start.x*10,y:start.y*10},length,angle);return {x:snap(p.x/10,grid/10),y:snap(p.y/10,grid/10)}}return drawCursor}
 function applyDrawConstraint(){const p=constrainedDrawPoint();if(!p||!drawing.length)return;setDrawing(d=>[...d,p]);setDrawCursor(null);setDrawLengthInput('');setDrawAngleInput('');setStatus('Сторона задана точно');}
 function closeDrawingWithConstraint(){if(drawing.length<2)return;const p=constrainedDrawPoint();if(p){const next=[...drawing,p];setDrawing(next);if(next.length>=3){setPoints(next);setHistory(h=>[...h.slice(-49),snapshot()]);setFuture([]);setDrawing([]);setDrawCursor(null);setTool('select');setStatus(`Контур замкнут · ${next.length} сторон`)}}}
 function finishDrawing(){if(drawing.length<3)return;commit(cloneP(drawing));setDrawing([]);setDrawCursor(null);setTool('select');setStatus(`Контур замкнут · ${drawing.length} сторон`)}
 function startDraw(e:ReactPointerEvent<SVGSVGElement>){if(tool!=='draw')return;const q=drawingPoint(pos(e));if(drawing.length>=3&&dist(q,drawing[0])<22){finishDrawing();return}setDrawing(d=>[...d,q]);setDrawCursor(null);setStatus(drawing.length===0?'Первая точка установлена':'Точка добавлена');setDrawLengthInput('');setDrawAngleInput('')}
 function moveDraw(e:ReactPointerEvent<SVGSVGElement>){if(tool!=='draw')return;setDrawCursor(drawingPoint(pos(e)))}
 function dragPoint(i:number,e:ReactPointerEvent<SVGCircleElement>){if(tool!=='select')return;e.stopPropagation();setSelectedPoint(i);const start=cloneP(points);const move=(ev:PointerEvent)=>{const p=pos(ev),n=cloneP(start);n[i]={x:snap(p.x,grid/10),y:snap(p.y,grid/10)};setPoints(n)};const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);setHistory(h=>[...h.slice(-49),{points:start,items:cloneI(items)}]);setFuture([])};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)}
 function startWallDrag(i:number,e:ReactPointerEvent<SVGLineElement>){if(tool!=='select')return;e.stopPropagation();const startPointer=pos(e),startPoints=cloneP(points);wallDragRef.current={index:i,startPointer,startPoints};setSelectedWall(i);setSelectedPoint(null);setSelectedItem(null);setStatus(`Стена ${i+1}: перемещение`);const move=(ev:PointerEvent)=>{const session=wallDragRef.current;if(!session)return;const next=dragWallFromStart(session.startPoints,session.index,session.startPointer,pos(ev),{orthogonal,minLength:30,grid:grid/10});setPoints(next)};const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);const session=wallDragRef.current;wallDragRef.current=null;if(!session)return;const current=pointsRef.current;const changed=current.some((p,j)=>p.x!==session.startPoints[j]?.x||p.y!==session.startPoints[j]?.y);if(changed){setHistory(h=>[...h.slice(-49),{points:cloneP(session.startPoints),items:cloneI(itemsRef.current)}]);setFuture([]);setStatus(`Стена ${i+1}: готово`)}else setStatus('')};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)}
 const pointsRef=useRef(points);const itemsRef=useRef(items);useEffect(()=>{pointsRef.current=points},[points]);useEffect(()=>{itemsRef.current=items},[items]);
 function addPointOnWall(i:number,p:Point){const a=points[i],b=points[(i+1)%points.length],vx=b.x-a.x,vy=b.y-a.y,t=Math.max(0,Math.min(1,((p.x-a.x)*vx+(p.y-a.y)*vy)/(vx*vx+vy*vy||1))),q={x:snap(a.x+vx*t,grid/10),y:snap(a.y+vy*t,grid/10)};commit([...points.slice(0,i+1),q,...points.slice(i+1)]);setSelectedPoint(i+1);setStatus('Добавлена вершина')}
 function wallDouble(i:number,e:ReactPointerEvent<SVGLineElement>){e.stopPropagation();if(tool==='draw')return;const p=pos(e);addPointOnWall(i,p)}
 function addItem(e:ReactPointerEvent<SVGSVGElement>){if(!['spot','chandelier','lightLine','cornice'].includes(tool))return;const p=pos(e),id=items.length?Math.max(...items.map(x=>x.id))+1:1,it:Item={id,type:tool,x:snap(p.x,grid/10),y:snap(p.y,grid/10)};if(tool==='lightLine'){it.x2=it.x+140;it.y2=it.y}if(tool==='cornice'){it.x2=it.x+90;it.y2=it.y}commit(points,[...items,it]);setSelectedItem(id);setTool('select')}
 function dragItem(id:number,e:ReactPointerEvent<SVGElement>){e.stopPropagation();if(tool!=='select')return;setSelectedItem(id);const base=items.find(x=>x.id===id);if(!base)return;const start=cloneI(items);const move=(ev:PointerEvent)=>{const p=pos(ev),dx=p.x-base.x,dy=p.y-base.y;setItems(start.map(x=>x.id===id?{...x,x:snap(p.x,grid/10),y:snap(p.y,grid/10),x2:x.x2===undefined?undefined:snap(x.x2+dx,grid/10),y2:x.y2===undefined?undefined:snap(x.y2+dy,grid/10)}:x))};const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);setHistory(h=>[...h.slice(-49),{points:cloneP(points),items:start}]);setFuture([])};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)}
 function deleteSelected(){if(selectedPoint!==null&&points.length>3){commit(points.filter((_,i)=>i!==selectedPoint));setSelectedPoint(null);return}if(selectedItem!==null){commit(points,items.filter(x=>x.id!==selectedItem));setSelectedItem(null)}}
 function updateWall(i:number,v:string){const mm=parseDimension(v);if(!mm||mm<100)return;const p=orthogonal&&points.length===4?resizeOrthogonalWall(toMm(points),i,mm):resizeWallKeepingAdjacent(toMm(points),i,mm);commit(fromMm(p))}
 function addSide(){const mm=parseDimension(sideLength),a=Number(sideAngle.replace(',','.'));if(!mm||!Number.isFinite(a)||!points.length)return;const last=points.at(-1)!,p=pointFromLengthAngle({x:last.x*10,y:last.y*10},mm,a);commit([...points,{x:snap(p.x/10,grid/10),y:snap(p.y/10,grid/10)}]);setSideLength('')}
 function newProject(){setProjectId('');setProjectName('Новая комната');setPoints(cloneP(initial));setItems([]);setVariants([{id:'standard',name:'Стандарт',points:cloneP(initial),items:[]}]);setActiveVariant('standard');setDrawing([]);setDrawCursor(null);setHistory([]);setFuture([]);setStatus('Новый проект')}
 function addVariant(){const id=`variant-${Date.now()}`;setVariants(v=>[...v,{id,name:`Вариант ${v.length+1}`,points:cloneP(points),items:cloneI(items)}]);setActiveVariant(id)}
 function switchVariant(id:string){const v=variants.find(x=>x.id===id);if(!v||id===activeVariant)return;setVariants(xs=>xs.map(x=>x.id===activeVariant?{...x,points:cloneP(points),items:cloneI(items)}:x));setPoints(cloneP(v.points));setItems(cloneI(v.items));setActiveVariant(id)}
 const diagonalRows=points.length>=3?[{id:1,a:0,b:2,lengthMm:Math.round(dist(points[0],points[2])*10)},...(points.length>=4?[{id:2,a:1,b:3,lengthMm:Math.round(dist(points[1],points[3])*10)}]:[])]:[];
 const previewStart=drawing.at(-1)??null;const constrainedPreview=constrainedDrawPoint();const previewPoint=constrainedPreview??drawCursor;const previewLength=previewStart&&previewPoint?Math.round(dist(previewStart,previewPoint)*10):0;const previewAngle=previewStart&&previewPoint?Math.round(Math.atan2(previewPoint.y-previewStart.y,previewPoint.x-previewStart.x)*180/Math.PI):0;const autoDiagonals=points.length>=4?points.slice(2,-1).map((p,i)=>({a:points[0],b:p,id:i})):[];
 return <main className="planner-page" tabIndex={0} onKeyDown={e=>{if((e.key==='Delete'||e.key==='Backspace')&&!['INPUT','TEXTAREA','SELECT'].includes((e.target as HTMLElement).tagName))deleteSelected();if(e.key==='Escape'){setDrawing([]);setDrawCursor(null);setDrawLengthInput('');setDrawAngleInput('');setTool('select');setStatus('Построение отменено')}if(e.key==='Enter'&&tool==='draw'){if(drawLengthInput||drawAngleInput)applyDrawConstraint();else finishDrawing();}}}>
 <header className="planner-header"><div className="planner-brand"><div className="planner-logo">P</div><div><strong>Potolok Planner</strong><span>Планировщик натяжных потолков</span></div></div><div className="planner-project"><label>Проект</label><input value={projectName} onChange={e=>setProjectName(e.target.value)}/></div><div className="planner-actions"><button onClick={newProject}>Новый</button><button onClick={()=>save()}>Сохранить</button><button onClick={undo} disabled={!history.length}>↶ Отмена</button><button onClick={redo} disabled={!future.length}>↷ Повтор</button><button className="primary" onClick={()=>window.print()}>Печать / PDF</button></div></header>
 <section className="planner-toolbar"><button className={tool==='select'?'active':''} onClick={()=>setTool('select')}>↖ Выбор</button><button className={tool==='draw'?'active':''} onClick={()=>{setTool('draw');setDrawing([]);setDrawCursor(null);setStatus('Кликните, чтобы задать первую точку')}}>⌘ Геометрия</button><button className={tool==='diagonal'?'active':''} onClick={()=>setTool('diagonal')}>⌁ Диагональ</button><span className="toolbar-divider"/><button className={orthogonal?'active':''} onClick={()=>setOrthogonal(x=>!x)}>□ Прямые углы</button><button onClick={()=>setShowAngles(x=>!x)}>∠ Углы</button><button onClick={()=>setShowDiagonals(x=>!x)}>⌁ Диагонали</button><span className="grid-control">Сетка <select value={grid} onChange={e=>setGrid(Number(e.target.value))}><option value={10}>10 мм</option><option value={50}>50 мм</option><option value={100}>100 мм</option></select></span><button onClick={()=>setZoom(x=>Math.max(.7,x-.1))}>−</button><button onClick={()=>setZoom(x=>Math.min(1.6,x+.1))}>＋</button><span className="planner-status">{status}</span></section>
 <div className="planner-grid"><aside className="planner-sidebar planner-left-panel">
   <section className="left-section drawing-precision"><h3>Точная сторона</h3><p>Задайте длину и угол следующей стороны. Enter применяет.</p><div className="precision-row"><input value={drawLengthInput} onChange={e=>setDrawLengthInput(e.target.value)} placeholder="Длина, мм"/><input value={drawAngleInput} onChange={e=>setDrawAngleInput(e.target.value)} placeholder="Угол, °"/><button onClick={applyDrawConstraint} disabled={!drawing.length||(!drawLengthInput&&!drawAngleInput)}>Применить</button></div><button className="element-btn" onClick={closeDrawingWithConstraint} disabled={drawing.length<2}>Замкнуть по текущей стороне</button></section><section className="left-section instruction-section"><h3>Инструкция</h3><p>{tool==='draw'?'Кликайте по точкам контура. Двигайте курсор — увидите длину и угол. Клик по первой точке закрывает контур. Enter — завершить, Esc — отменить.':'Нажмите, чтобы добавить углы комнаты. Точки привязываются к сетке.'}</p></section>
   <section className="left-section"><h3>Настройки построителя</h3><label className="switch-row"><span>Вычислять длины сторон</span><button type="button" className={showSideLengths?'mini-switch on':'mini-switch'} onClick={()=>setShowSideLengths(v=>!v)}><i/></button></label><label className="switch-row"><span>Прямые углы</span><button type="button" className={orthogonal?'mini-switch on':'mini-switch'} onClick={()=>setOrthogonal(v=>!v)}><i/></button></label></section>
   <section className="left-section"><h3>Информация о чертеже</h3><div className="drawing-info"><div>Общая S= <b>{area.toFixed(2)} м²</b> P= <b>{perimeter.toFixed(2)} м</b></div><div>Сторон: <b>{points.length}</b> · Углов: <b>{points.length}</b></div><div>Масштаб: <b>1:10</b></div></div></section>
   <section className="left-section"><div className="section-title-row"><h3>Стороны</h3><label className="compact-toggle"><span>Показывать длины</span><button type="button" className={showSideLengths?'mini-switch on':'mini-switch'} onClick={()=>setShowSideLengths(v=>!v)}><i/></button></label></div><div className="side-list">{points.map((p,i)=>{const q=points[(i+1)%points.length],length=Math.round(dist(p,q)*10);return <div key={i} className={selectedWall===i?'side-row selected':'side-row'}><button className="side-edit" onClick={()=>{setSelectedWall(i);setSelectedPoint(null);setSelectedItem(null)}}>✎</button><input aria-label={`Сторона ${i+1}`} defaultValue={length} onBlur={e=>updateWall(i,e.target.value)}/><span>мм</span></div>})}</div><div className="left-add-side"><input value={sideLength} onChange={e=>setSideLength(e.target.value)} placeholder="Добавить сторону"/><input value={sideAngle} onChange={e=>setSideAngle(e.target.value)} placeholder="угол"/><button onClick={addSide}>＋</button></div></section>
   <section className="left-section"><div className="section-title-row"><h3>Диагонали</h3><button className="section-icon-button" onClick={()=>setTool('diagonal')}>✎</button></div><label className="switch-row compact"><span>Показывать диагонали</span><button type="button" className={showDiagonals?'mini-switch on':'mini-switch'} onClick={()=>setShowDiagonals(v=>!v)}><i/></button></label><div className="diagonal-mode">Режим построения диагоналей <select value={selectedDiagonal} onChange={e=>setSelectedDiagonal(Number(e.target.value))}><option value={1}>Треугольник</option><option value={2}>По сторонам</option></select></div><div className="diagonal-list">{diagonalRows.map(d=><div key={d.id} className={selectedDiagonal===d.id?'diagonal-row selected':'diagonal-row'}><span className="diag-name">{String.fromCharCode(65+d.a)}{String.fromCharCode(65+d.b)}</span><input value={d.lengthMm} readOnly/><span>мм</span><button onClick={()=>{setSelectedDiagonal(d.id);setTool('diagonal')}}>✎</button></div>)}</div></section>
   <section className="left-section left-tools-section"><h3>Элементы</h3>{(Object.keys(labels) as ElementType[]).map(t=><button key={t} className="element-btn" onClick={()=>setTool(t)}>＋ {labels[t]}</button>)}</section><section className="left-section"><h3>Варианты</h3>{variants.map(v=><button key={v.id} className={v.id===activeVariant?'element-btn active':'element-btn'} onClick={()=>switchVariant(v.id)}>{v.name}</button>)}<button className="element-btn" onClick={addVariant}>＋ Вариант</button></section>
 </aside>
 <section className="planner-canvas-wrap"><svg ref={svgRef} className={`planner-canvas ${tool==='draw'?'drawing-mode':''}`} viewBox={`0 0 ${W} ${H}`} onPointerDown={e=>{if(tool==='draw')startDraw(e);else addItem(e)}} onPointerMove={moveDraw} onPointerLeave={()=>tool==='draw'&&setDrawCursor(null)} style={{transform:`scale(${zoom})`,transformOrigin:'center'}}><defs><pattern id="grid-main" width={grid/10} height={grid/10} patternUnits="userSpaceOnUse"><path d={`M ${grid/10} 0 L 0 0 0 ${grid/10}`} fill="none" stroke="currentColor" opacity=".08"/></pattern></defs><rect width={W} height={H} fill="url(#grid-main)"/>
 {points.map((p,i)=>{const q=points[(i+1)%points.length],len=dist(p,q);return <g key={i}><line x1={p.x} y1={p.y} x2={q.x} y2={q.y} className={selectedWall===i?'room-wall selected':'room-wall'} onPointerDown={e=>startWallDrag(i,e)} onClick={e=>{e.stopPropagation();setSelectedWall(i);setSelectedPoint(null);setSelectedItem(null)}} onDoubleClick={e=>wallDouble(i,e)}/>{showSideLengths&&<text x={(p.x+q.x)/2} y={(p.y+q.y)/2-8} className="dimension-label" textAnchor="middle">{Math.round(len*10)} мм</text>}{showAngles&&<text x={p.x+12} y={p.y+18} className="angle-label">{angleAt(points,i).toFixed(0)}°</text>}</g>})}
 {points.map((p,i)=><circle key={`p${i}`} cx={p.x} cy={p.y} r={selectedPoint===i?10:7} className={selectedPoint===i?'room-point selected':'room-point'} onPointerDown={e=>dragPoint(i,e)} onClick={e=>e.stopPropagation()}/>)}
 {drawing.length>0&&<><polyline points={drawing.map(p=>`${p.x},${p.y}`).join(' ')} className="room-wall selected"/>{drawing.map((p,i)=><circle key={`d${i}`} cx={p.x} cy={p.y} r={i===0&&drawCursor&&dist(p,drawCursor)<22?10:7} className="room-point selected"/>)}{previewStart&&previewPoint&&<><line x1={previewStart.x} y1={previewStart.y} x2={previewPoint.x} y2={previewPoint.y} className="draw-preview-line"/><circle cx={previewPoint.x} cy={previewPoint.y} r={5} className="room-point selected"/><rect x={(previewStart.x+previewPoint.x)/2-60} y={(previewStart.y+previewPoint.y)/2-34} width="120" height="44" rx="6" className="draw-preview-box"/><text x={(previewStart.x+previewPoint.x)/2} y={(previewStart.y+previewPoint.y)/2-16} textAnchor="middle" className="draw-preview-text">{previewLength} мм</text><text x={(previewStart.x+previewPoint.x)/2} y={(previewStart.y+previewPoint.y)/2+2} textAnchor="middle" className="draw-preview-text">{previewAngle}°</text></>}</>}
 {showDiagonals&&points.length>=4&&autoDiagonals.map(d=><line key={`auto-${d.id}`} x1={d.a.x} y1={d.a.y} x2={d.b.x} y2={d.b.y} className="diagonal-line"/>)}{showDiagonals&&points.length>=3&&<><line x1={points[0].x} y1={points[0].y} x2={points[2].x} y2={points[2].y} className="diagonal-line"/><text x={(points[0].x+points[2].x)/2+8} y={(points[0].y+points[2].y)/2-8} className="dimension-label">{Math.round(dist(points[0],points[2])*10)} мм</text></>}
 {items.map(it=>it.type==='spot'?<circle key={it.id} cx={it.x} cy={it.y} r={8} className={selectedItem===it.id?'ceiling-element selected':'ceiling-element'} onPointerDown={e=>dragItem(it.id,e)}/>:it.type==='chandelier'?<circle key={it.id} cx={it.x} cy={it.y} r={15} className={selectedItem===it.id?'ceiling-element selected':'ceiling-element'} onPointerDown={e=>dragItem(it.id,e)}/>:<line key={it.id} x1={it.x} y1={it.y} x2={it.x2} y2={it.y2} className={selectedItem===it.id?'ceiling-element selected':'ceiling-element'} onPointerDown={e=>dragItem(it.id,e)}/>)}<text x={20} y={30} className="canvas-caption">{tool==='draw'?'ПОСТРОЕНИЕ КОНТУРА — Enter завершить · Esc отмена':tool==='select'?'CAD-РЕЖИМ':'РЕЖИМ '+tool.toUpperCase()}</text></svg></section>
 <aside className="planner-sidebar"><div className="panel-title">Параметры</div>{selectedWall!==null&&<div className="property-card"><b>Сторона {selectedWall+1}</b><label>Длина<input key={`${selectedWall}-${Math.round(dist(points[selectedWall],points[(selectedWall+1)%points.length])*10)}`} defaultValue={Math.round(dist(points[selectedWall],points[(selectedWall+1)%points.length])*10)} onBlur={e=>updateWall(selectedWall,e.target.value)}/><span>мм</span></label><div>Угол: {angleAt(points,selectedWall).toFixed(1)}°</div></div>}{selectedPoint!==null&&<div className="property-card"><b>Вершина {selectedPoint+1}</b><label>X<input value={Math.round(points[selectedPoint].x*10)} onChange={e=>{const n=cloneP(points);n[selectedPoint].x=(parseFloat(e.target.value)||0)/10;setPoints(n)}}/><span>мм</span></label><label>Y<input value={Math.round(points[selectedPoint].y*10)} onChange={e=>{const n=cloneP(points);n[selectedPoint].y=(parseFloat(e.target.value)||0)/10;setPoints(n)}}/><span>мм</span></label><button onClick={deleteSelected} disabled={points.length<=3}>Удалить вершину</button></div>}{selectedItem!==null&&(()=>{const it=items.find(x=>x.id===selectedItem);if(!it)return null;return <div className="property-card"><b>{labels[it.type]}</b><label>X<input value={Math.round(it.x*10)} onChange={e=>{const n=parseFloat(e.target.value);if(Number.isFinite(n))setItems(items.map(x=>x.id===it.id?{...x,x:n/10}:x))}}/><span>мм</span></label><label>Y<input value={Math.round(it.y*10)} onChange={e=>{const n=parseFloat(e.target.value);if(Number.isFinite(n))setItems(items.map(x=>x.id===it.id?{...x,y:n/10}:x))}}/><span>мм</span></label>{it.x2!==undefined&&<><label>X2<input value={Math.round(it.x2*10)} onChange={e=>{const n=parseFloat(e.target.value);if(Number.isFinite(n))setItems(items.map(x=>x.id===it.id?{...x,x2:n/10}:x))}}/><span>мм</span></label><label>Y2<input value={Math.round(it.y2!*10)} onChange={e=>{const n=parseFloat(e.target.value);if(Number.isFinite(n))setItems(items.map(x=>x.id===it.id?{...x,y2:n/10}:x))}}/><span>мм</span></label></>}<div>Ед.: {units[it.type]} · {prices[it.type]} ₽</div><button onClick={deleteSelected}>Удалить элемент</button></div>})()}<div className="property-card"><b>Смета</b><div>Продажа: <strong>{Math.round(estimate.totalSell).toLocaleString('ru-RU')} ₽</strong></div><div>Себестоимость: {Math.round(estimate.totalCost).toLocaleString('ru-RU')} ₽</div><div>Маржа: {Math.round(estimate.margin).toLocaleString('ru-RU')} ₽</div><details><summary>Позиции</summary>{estimate.items.map((x:any)=><div key={x.id}>{x.name}: {Number(x.quantity).toFixed(2)} {x.unit}</div>)}</details></div><div className="property-card"><b>Проекты</b>{projects.slice(0,8).map(p=><button key={p.id} className="element-btn" onClick={()=>openProject(p)}>{p.name}</button>)}</div></aside></div></main>;
}
