'use client';

import { PointerEvent, useMemo, useState } from 'react';
import EstimatePanel from './components/EstimatePanel';
import CeilingVariants, { CeilingVariant } from './components/CeilingVariants';
import { defaultCatalog } from '../lib/catalog';
import { angleAt, distance, polygonArea, polygonPerimeter, snapPoint } from '../lib/geometry';

type Point={x:number;y:number};
type ElementType='spot'|'chandelier'|'cornice';
type CeilingElement={id:number;type:ElementType;x:number;y:number};
const W=800,H=600,initialPoints:Point[]=[{x:0,y:0},{x:5000,y:0},{x:5000,y:3600},{x:0,y:3600}];
const labels:Record<ElementType,string>={spot:'Светильник',chandelier:'Люстра',cornice:'Карниз'};

export default function Home(){
 const [points,setPoints]=useState<Point[]>(initialPoints),[selectedWall,setSelectedWall]=useState(0),[selectedPoint,setSelectedPoint]=useState(0),[dragging,setDragging]=useState<number|null>(null),[elements,setElements]=useState<CeilingElement[]>([]),[selectedElement,setSelectedElement]=useState<number|null>(null),[nextId,setNextId]=useState(1),[name,setName]=useState('Новая комната'),[status,setStatus]=useState('');
 const [variants,setVariants]=useState<CeilingVariant[]>([{id:'standard',name:'Стандарт',price:0,active:true}]),[activeVariant,setActiveVariant]=useState('standard');
 const area=useMemo(()=>polygonArea(points)/1e6,[points]),perimeter=useMemo(()=>polygonPerimeter(points)/1000,[points]);
 const bounds=useMemo(()=>{const xs=points.map(p=>p.x),ys=points.map(p=>p.y),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),scale=Math.min(660/Math.max(maxX-minX,1),460/Math.max(maxY-minY,1));return{minX,minY,scale,ox:(W-(maxX-minX)*scale)/2,oy:(H-(maxY-minY)*scale)/2}},[points]);
 const toSvg=(p:Point)=>({x:bounds.ox+(p.x-bounds.minX)*bounds.scale,y:bounds.oy+(p.y-bounds.minY)*bounds.scale});
 const fromEvent=(e:PointerEvent<SVGCircleElement>)=>{const svg=e.currentTarget.ownerSVGElement;if(!svg)return null;const r=svg.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*W-bounds.ox,b:(e.clientY-r.top)/r.height*H-bounds.oy};};
 const quantities=useMemo(()=>({canvas:area,profile:perimeter,insert:perimeter,fastener:perimeter,spot:elements.filter(e=>e.type==='spot').length,chandelier:elements.filter(e=>e.type==='chandelier').length,cornice:elements.filter(e=>e.type==='cornice').length,installation:area}),[area,perimeter,elements]);
 const variantPrice=useMemo(()=>defaultCatalog.reduce((s,i)=>s+(quantities[i.id as keyof typeof quantities]||0)*i.sellPrice,0),[quantities]);
 function movePoint(i:number,e:PointerEvent<SVGCircleElement>){const p=fromEvent(e);if(!p)return;setPoints(c=>c.map((v,j)=>j===i?snapPoint({x:Math.max(0,p.x/bounds.scale+bounds.minX),y:Math.max(0,p.b/bounds.scale+bounds.minY)},10):v))}
 function addCorner(){const n=(selectedWall+1)%points.length,a=points[selectedWall],b=points[n],m={x:(a.x+b.x)/2,y:(a.y+b.y)/2};setPoints(c=>[...c.slice(0,n),m,...c.slice(n)]);setSelectedPoint(n);setSelectedWall(n)}
 function addElement(type:ElementType){const x=points.reduce((s,p)=>s+p.x,0)/points.length,y=points.reduce((s,p)=>s+p.y,0)/points.length;setElements(c=>[...c,{id:nextId,type,x,y}]);setSelectedElement(nextId);setNextId(n=>n+1)}
 function moveElement(id:number,e:PointerEvent<SVGGElement>){const svg=e.currentTarget.ownerSVGElement;if(!svg)return;const r=svg.getBoundingClientRect();const x=(e.clientX-r.left)/r.width*W,y=(e.clientY-r.top)/r.height*H;setElements(c=>c.map(v=>v.id===id?{...v,x:(x-bounds.ox)/bounds.scale+bounds.minX,y:(y-bounds.oy)/bounds.scale+bounds.minY}:v))}
 function duplicateVariant(id:string){const v=variants.find(x=>x.id===id);if(!v)return;const copy={...v,id:`${id}-${Date.now()}`,name:`${v.name} — копия`,active:false};setVariants(x=>[...x.map(v=>({...v,active:false})),copy]);setActiveVariant(copy.id)}
 function addVariant(){const id=`variant-${Date.now()}`;setVariants(x=>[...x.map(v=>({...v,active:false})),{id,name:`Вариант ${x.length+1}`,price:variantPrice,active:true}]);setActiveVariant(id)}
 function reset(){setPoints(initialPoints);setElements([]);setSelectedPoint(0);setSelectedWall(0);setSelectedElement(null);setStatus('Новый проект')}
 return <main className="app-shell">
  <header className="topbar"><div className="brand"><span className="brand-mark">P</span><span>Potolok Planner</span></div><div className="project-name"><input value={name} onChange={e=>setName(e.target.value)} aria-label="Название проекта"/></div><div className="top-actions"><button className="ghost" onClick={reset}>Новый</button><button className="ghost" onClick={()=>window.print()}>PDF / Печать</button><button className="primary" onClick={()=>setStatus('Изменения сохранены')}>Сохранить</button></div></header>
  <CeilingVariants variants={variants.map(v=>v.id===activeVariant?{...v,active:true,price:variantPrice}:v)} activeId={activeVariant} onSelect={id=>setActiveVariant(id)} onDuplicate={duplicateVariant} onAdd={addVariant}/>
  <section className="workspace"><aside className="panel left-panel"><div className="panel-title">Конструктор</div><label>Название<input value={name} onChange={e=>setName(e.target.value)}/></label><div className="section-title">Геометрия</div><div className="stat"><span>Площадь</span><strong>{area.toFixed(2)} м²</strong></div><div className="stat"><span>Периметр</span><strong>{perimeter.toFixed(2)} м</strong></div><div className="stat"><span>Выбранная стена</span><strong>{Math.round(distance(points[selectedWall],points[(selectedWall+1)%points.length]))} мм</strong></div><div className="button-row"><button className="add-button" onClick={addCorner}>＋ Угол</button><button className="delete-button" disabled={points.length<=3} onClick={()=>{if(points.length>3)setPoints(p=>p.filter((_,i)=>i!==selectedPoint))}}>− Угол</button></div><div className="section-title">Элементы потолка</div><button className="feature" onClick={()=>addElement('spot')}>＋ Светильник</button><button className="feature" onClick={()=>addElement('chandelier')}>＋ Люстра</button><button className="feature" onClick={()=>addElement('cornice')}>＋ Карниз</button>{selectedElement!==null&&<button className="delete-feature" onClick={()=>{setElements(x=>x.filter(e=>e.id!==selectedElement));setSelectedElement(null)}}>Удалить выбранный элемент</button>}<div className="section-title">Углы</div><div className="angle-list">{points.map((p,i)=><span key={i}>∠{i+1}: {angleAt(points[(i-1+points.length)%points.length],p,points[(i+1)%points.length]).toFixed(1)}°</span>)}</div></aside>
   <div className="canvas-area"><div className="canvas-toolbar"><span>2D-план · {name}</span><span className="muted">Шаг 10 мм · {status}</span></div><div className="drawing-wrap"><svg className="drawing" viewBox={`0 0 ${W} ${H}`} onPointerUp={()=>setDragging(null)} onPointerCancel={()=>setDragging(null)}><defs><pattern id="grid" width="25" height="25" patternUnits="userSpaceOnUse"><path d="M25 0H0V25" fill="none" stroke="currentColor" strokeOpacity=".07"/></pattern></defs><rect width={W} height={H} fill="url(#grid)"/><polygon points={points.map(toSvg).map(p=>`${p.x},${p.y}`).join(' ')} className="room"/>{points.map((p,i)=>{const n=points[(i+1)%points.length],a=toSvg(p),b=toSvg(n),m={x:(a.x+b.x)/2,y:(a.y+b.y)/2};return <g key={i}><line x1={a.x} y1={a.y} x2={b.x} y2={b.y} className={selectedWall===i?'wall-hit selected-wall':'wall-hit'} onPointerDown={()=>{setSelectedWall(i);setSelectedPoint(i)}}/><text x={m.x} y={m.y-12} className="dimension-text" textAnchor="middle">{Math.round(distance(p,n))} мм</text><circle cx={a.x} cy={a.y} r={selectedPoint===i?10:8} className={selectedPoint===i?'handle selected':'handle'} onPointerDown={e=>{e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId);setSelectedPoint(i);setSelectedWall(i);setDragging(i)}} onPointerMove={e=>dragging===i&&movePoint(i,e)} onPointerUp={e=>{try{e.currentTarget.releasePointerCapture(e.pointerId)}catch{};setDragging(null)}}/></g>})}{elements.map(el=>{const p=toSvg(el),sel=selectedElement===el.id;return <g key={el.id} transform={`translate(${p.x} ${p.y})`} className={`ceiling-element ${sel?'selected-element':''}`} onPointerDown={e=>{e.stopPropagation();setSelectedElement(el.id)}} onPointerMove={e=>sel&&moveElement(el.id,e)}>{el.type==='spot'?<><circle r="14" className="spot-symbol"/><circle r="4" className="spot-core"/></>:el.type==='chandelier'?<><circle r="22" className="chandelier-symbol"/><path d="M-12 8Q0-8 12 8M-8 12Q0 0 8 12" className="chandelier-lines"/></>:<><rect x="-55" y="-7" width="110" height="14" rx="7" className="cornice-symbol"/><text y="-15" textAnchor="middle" className="element-label">карниз</text></>}</g>})}<text x={W/2} y={H/2+8} className="area-text" textAnchor="middle">{area.toFixed(2)} м²</text></svg></div></div>
   <EstimatePanel catalog={defaultCatalog} quantities={quantities} onQuantityChange={()=>{}}/>
  </section>
 </main>
}
